services:
  alex:
    build:
      context: .
      target: alex
    expose:
      - 5000
  carla:
    build:
      context: .
      target: carla
    expose:
      - 5000
  algo-eval:
    build:
      context: .
      target: algo-eval
    ports:
      - 5001:5000
  algo-eval-storage:
    build:
      context: .
      target: algo-eval-storage
    expose:
      - 5000
